### Create1
POST http://localhost:8080/payments
Content-Type: application/json
Accept: application/json

{
  "status": "APPROVED"
}

### Create2
POST http://localhost:8080/payments
Content-Type: application/json
Accept: application/json

{
  "status": "APPROVED"
}
> {% client.global.set("id", response.body.id); %}

### Update
PUT http://localhost:8080/payments/{{id}}
Content-Type: application/json
Accept: application/json

{
  "status": "REJECTED"
}

### List 1 items per page
GET http://localhost:8080/payments?size=1&page=1
Accept: application/json

### List 2 items per page
GET http://localhost:8080/payments?size=2&page=1
Accept: application/json

