### Create1
POST http://localhost:8080/payments
Content-Type: application/json
Accept: application/json

{
  "status": "APPROVED"
}

### Create2
POST http://localhost:8080/payments
Content-Type: application/json
Accept: application/json

{
  "status": "APPROVED"
}
> {% client.global.set("reference", response.body.reference); %}

### Update
PUT http://localhost:8080/payments/{{reference}}
Content-Type: application/json
Accept: application/json

{
  "status": "REJECTED"
}

### List
GET http://localhost:8080/payments?size=2&page=1&sort=reference,ASC&rsql=status=="REJECTED"
Accept: application/json

